import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "So entstehen unsere Empfehlungen", description: "Gewichtungen, Ausschlussregeln, Datenquellen und Grenzen des Bilderrahmen-Finders transparent erklärt." };

export default function MethodPage() {
  const weights = [["Einsatz", 28, "Foto, Poster, Galerie, Dokument oder digital"], ["Format", 24, "Exakte Größe vor angrenzenden Formaten"], ["Budget", 18, "Preisbewusst, ausgewogen oder Premium"], ["Stil", 12, "Minimal, warm, klassisch oder ausdrucksstark"], ["Farbe", 8, "Farbwunsch und neutrale Alternativen"], ["Platzierung", 5, "Wand, Tisch oder flexibel"], ["Datenklarheit", 5, "Erkennbare Maße, Materialien und Farben"]];
  return <main className="method-page shell"><header className="page-intro"><p className="eyebrow">Nachvollziehbar statt geheim</p><h1>Unsere Empfehlung ist eine Rechnung – kein Bauchgefühl.</h1><p>Wir ordnen Produkte regelbasiert nach deinen Antworten. Eine hohe Punktzahl bedeutet gute Passung zu deinem Fall, nicht automatisch bessere Qualität.</p></header><section className="weight-list">{weights.map(([label, points, note]) => <article key={String(label)}><strong>{points}</strong><div><h2>{label}</h2><p>{note}</p></div><span style={{ width: `${Number(points) * 3}%` }} /></article>)}</section><section className="method-grid"><article><span>01</span><h2>Ausschlussregeln zuerst</h2><p>Wenn du einen digitalen Rahmen suchst, werden klassische Rahmen ausgeschlossen – und umgekehrt. So kann eine hohe Bewertung keine grundlegende Fehlpassung überdecken.</p></article><article><span>02</span><h2>Unsicherheit ist erlaubt</h2><p>„Ich bin nicht sicher“ wird neutral behandelt. Das betreffende Kriterium dominiert dann nicht die Auswahl; die übrigen Antworten gewinnen an Bedeutung.</p></article><article><span>03</span><h2>Drei Perspektiven statt einer Liste</h2><p>Wir zeigen den besten Gesamt-Treffer, eine preisbewusste und eine besondere Alternative. Dadurch bleiben echte Entscheidungen möglich.</p></article></section><section className="limits"><h2>Grenzen der Empfehlung</h2><ul><li>Wir testen die Produkte nicht selbst und vergeben keine erfundenen Testsiegel.</li><li>Amazon-Preise, Bewertungen und Verfügbarkeit sind dynamisch.</li><li>Unklare Produktangaben werden sichtbar als solche benannt.</li><li>Für wertvolle Kunst, Brandschutz oder besondere Wände kann fachliche Beratung sinnvoll sein.</li></ul></section><Link className="button button-primary" href="/finder">Finder mit dieser Logik starten</Link></main>;
}
